name: checkout
on: workflow_dispatch

jobs:
  no-checkout: # job 이름
    runs-on: ubuntu-latest
    steps:
    - name: check file list
      run: |
        ls -al
        whoami
        pwd
        cat README.md
  
  checkout: # job 이름
    runs-on: ubuntu-latest
    steps:
    - name: use checkout action # step 이름
      uses: actions/checkout@v4
    - name: check file list
      run: |
        whoami
        pwd
        cat README.md