name: issue-workflow
on:
  issues:
    types: [opend]

jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run:
        echo hello world
        echo github action
